<!--<div data-mage-init='{"slickSlider": {"message": "HELLO WORLD!"}}'>-->
<!--    Content-->
<!--</div>-->

<div class="slick-container">
    <di class="slick">
        <ul class="products-slider" id="products-slider">
<!--            <li>SLIDER 1</li>-->
<!--            <li>SLIDER 2</li>-->
<!--            <li>SLIDER 3</li>-->
<!--            <li>SLIDER 4</li>-->
<!--            <li>SLIDER 5</li>-->
<!--            <li>SLIDER 6</li>-->
<!--            <li>SLIDER 7</li>-->
<!--            <li>SLIDER 8</li>-->
<!--            <li>SLIDER 9</li>-->

            <?php
            /** @var \M2Dev\SlickSlider\Block\ProductsList $productCollection */
            $productCollection = $block->getProductCollection();
            foreach ($productCollection as $product): ?>
            <div class="title" style="border: 1px solid;">
                <strong><?= $product->getName() ?></strong>
            </div>
            <?php
//            var_dump($product->getData());
            ?>
            <?php endforeach; ?>

            <!--?php
            echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('catalog_products_list')
                ->toHtml();
            ?-->

        </ul>
    </di>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function($) {
        'use strict';

        $(function() {
           console.log('AAC SLICK!');
           $(".products-slider").slick({
               slidesToShow: 5,
               slidesToScroll: 1,
               // infinite: true,
               autoplay: true,
               autoplaySpeed: 2000,
           });
        });
    });
</script>